[package]
name = "gas_price"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
ethers = { version = "2", features = ["rustls"] }
anyhow = "1"
